export const data = [
  {
    "name": "Photo 1",
    "url": "/images/acarbose.png",
    "description": "Photo 1 description",
    "date": "2020-01-01",
    "type": "image/png",
  },
  {
    "name": "Photo 2",
    "url": "/images/boots.jpg",
    "description": "Photo 2 description",
    "date": "2020-01-02",
    "type": "image/jpg",
  },
  {
    "name": "Photo 3",
    "url": "/images/banner-picture.jpeg",
    "description": "Photo 3 description",
    "date": "2020-01-03",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 4",
    "url": "/images/chill vibes.jpeg",
    "description": "Photo 4 description",
    "date": "2020-01-04",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 5",
    "url": "/images/christmasgrenade.jpg",
    "description": "Photo 5 description",
    "date": "2020-01-05",
    "type": "image/jpg",
  },
  {
    "name": "Photo 6",
    "url": "/images/coffee.png",
    "description": "Photo 6 description",
    "date": "2020-01-06",
    "type": "image/png",
  },
  {
    "name": "Photo 7",
    "url": "/images/current.png",
    "description": "Photo 7 description",
    "date": "2020-01-07",
    "type": "image/png",
  },
  {
    "name": "Photo 8",
    "url": "/images/decolgen.jpg",
    "description": "Photo 8 description",
    "date": "2020-01-08",
    "type": "image/jpg",
  },
  {
    "name": "Photo 9",
    "url": "/images/ez.png",
    "description": "Photo 9 description",
    "date": "2020-01-09",
    "type": "image/png",
  }
]
